name: SQUID
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - argon2-cffi=21.3.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.1.0
  - boost=1.74.0
  - boost-cpp=1.74.0
  - brotli=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - cairo=1.16.0
  - charset-normalizer=2.0.4
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - executing=0.8.3
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - icu=68.1
  - idna=3.3
  - intel-openmp=2021.4.0
  - ipython_genutils=0.2.0
  - jpeg=9e
  - jupyter_client=7.2.2
  - jupyter_core=4.10.0
  - jupyterlab_pygments=0.1.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - mkl=2021.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - nettle=3.7.3
  - networkx=2.7.1
  - numpy-base=1.22.3
  - openh264=2.1.1
  - openssl=1.1.1q
  - packaging=21.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pixman=0.40.0
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - python=3.10.4
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - python_abi=3.10
  - pytorch=1.11.0=py3.10_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - rdkit=2022.03.2
  - readline=8.1.2
  - requests=2.27.1
  - send2trash=1.8.0
  - six=1.16.0
  - soupsieve=2.3.1
  - sqlite=3.38.3
  - stack_data=0.2.0
  - tk=8.6.12
  - traitlets=5.1.1
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - tzdata=2022a
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - argon2-cffi-bindings==21.2.0
    - beautifulsoup4==4.11.1
    - bottleneck==1.3.4
    - brotlipy==0.7.0
    - certifi==2022.6.15
    - cffi==1.15.0
    - cryptography==37.0.1
    - debugpy==1.5.1
    - dill==0.3.5.1
    - entrypoints==0.4
    - fuzzywuzzy==0.18.0
    - greenlet==1.1.1
    - ipykernel==6.9.1
    - ipython==8.4.0
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.1.0
    - jsonschema==4.4.0
    - jupyter-client==7.2.2
    - jupyter-core==4.10.0
    - kiwisolver==1.4.2
    - markupsafe==2.1.1
    - matplotlib==3.5.1
    - mistune==0.8.4
    - mkl-fft==1.3.1
    - mkl-random==1.2.2
    - mkl-service==2.4.0
    - multiprocess==0.70.13
    - nbclient==0.5.13
    - nbconvert==6.4.4
    - nbformat==5.3.0
    - nest-asyncio==1.5.5
    - notebook==6.4.11
    - numexpr==2.7.3
    - numpy==1.22.3
    - openeye-toolkits==2022.1.1
    - openeye-toolkits-python3-linux-x64==2022.1.1
    - pandas==1.4.2
    - pathos==0.2.9
    - pillow==9.0.1
    - pip==21.2.4
    - pox==0.3.1
    - ppft==1.7.6.5
    - pycairo==1.19.1
    - pyparsing==3.0.9
    - pyrsistent==0.18.0
    - pysocks==1.7.1
    - pytdc==0.3.7
    - pytz==2022.1
    - pyzmq==23.2.0
    - rdkit-pypi==2022.3.5
    - reportlab==3.5.67
    - scikit-learn==1.1.1
    - scipy==1.8.1
    - seaborn==0.12.0
    - setuptools==61.2.0
    - sqlalchemy==1.4.32
    - terminado==0.13.1
    - testpath==0.6.0
    - threadpoolctl==3.1.0
    - torch==1.11.0
    - torch-geometric==2.0.4
    - torch-scatter==2.0.9
    - torch-sparse==0.6.13
    - torchaudio==0.11.0
    - torchvision==0.12.0
    - tornado==6.1
    - tqdm==4.64.0
    - urllib3==1.26.9
    - webencodings==0.5.1
